services:
  - type: web
    name: xss-ctf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set this securely in the Render dashboard!
      - key: SECRET_KEY
        generateValue: true # Render will automatically generate a strong secret key
